- templates/ConfluenceDataCenter.template
- templates/quickstart-confluence-master.template
@avattathil Please help me to review and merge this
> Update description for parameters and make sure those params are same on Confluence template and quickstart template

- templates/ConfluenceDataCenter.template
- Synchrony restart issue
- Collectd config issue
> Update AMIs as we fixed couples issues

- .gitmodules
- templates/ConfluenceDataCenter.template
- templates/quickstart-confluence-master.template
- Added S3 portability changes
> - Added linux-bastion and aws-vpc submodules

- templates/ConfluenceDataCenter.template
- templates/quickstart-confluence-master.template
adding 1 more parameter which allows user to use custom DNS via hosted zone. @avattathil please help me to review and approve it
> CONFSERVER-52540 - Support custom DNS for Confluence stack

- templates/ConfluenceDataCenter.template
- templates/quickstart-confluence-master.template
@avattathil please help me to review and merge this pr
> Fixed bug with optional parameter and update parameter descriptions

- templates/ConfluenceDataCenter.template
More detail could be found here https://jira.atlassian.com/browse/CONFSRVDEV-2376. 
Hi @avattathil, please help me to review and approve this change.
> Update new AMI which fix for Synchrony startup problem with Conf 6.4

- templates/ConfluenceDataCenter.template
Hi @avattathil, please help me to review and approve this PR
> CONFSRVDEV-1861 - support Synchrony master

- templates/quickstart-confluence-master-with-vpc.template.yaml
- templates/quickstart-confluence-master.template.yaml
This PR updates Confluence version to the latest released version.
> DCD-98: Update product versions to the latest available

- templates/quickstart-confluence-master-with-vpc.template.yaml
> DC-94: Add missing label and refactor out some orphaned params.

- templates/quickstart-confluence-master.template.yaml
Fix the generate URL for Synchrony, and update to AMIs with startup script fixes.
> DCD-160: Fix for Synchrony URL generation, and update AMIs

- templates/quickstart-confluence-master.template.yaml
Reverts aws-quickstart/quickstart-atlassian-confluence#38
> Revert "Refactor RDS provisioning into nested stack"

- templates/quickstart-confluence-master.template.yaml
More information: https://alas.aws.amazon.com/ALAS-2019-1205.html
> DCD-345: Update AMIs kernel version to `4.14.114-83.126.amzn1.x86_64`

- templates/quickstart-confluence-master-with-vpc.template.yaml
Similar to changes made in workload template; also changed DBPassword description to say "user account" instead of "master account."
*Issue #, if available:*
> Minor tweaks

- templates/quickstart-confluence-master-with-vpc.template.yaml
> Remove parameter in master template that has been removed in subtemplate

- templates/quickstart-confluence-master-with-vpc.template.yaml
- templates/quickstart-confluence-master.template.yaml
> Add missing jvm heap memory allocation mapping for c4.large instance class

- templates/quickstart-confluence-master-with-vpc.template.yaml
- templates/quickstart-confluence-master.template.yaml
https://regexr.com/4m291 - links to the regex playground
> DCD-678: Adds a better password regex constrarint for DB password 

- templates/quickstart-confluence-master-with-vpc.template.yaml
- templates/quickstart-confluence-master.template.yaml
https://bitbucket.org/atlassian/atlassian-aws-deployment/issues/40/jira-quickstart-template-ssh-escaping
> Update DBStorage to 200GB and quote SSH key

- README.md
- templates/quickstart-confluence-master.template.yaml
Update ASI and remove unnecessary DatabaseIdentifier
> Update ASI and remove unnecessary DatabaseIdentifier

- templates/quickstart-confluence-master-with-vpc.template.yaml
- templates/quickstart-confluence-master.template.yaml
KeyPairName description should be different for "with ASI" (required) and "without ASI" (optional) deployments. 
Also, changed the resource type so it's a dropdown list in "with ASI" deployments.
> Edited description and Type of KeyPairName parameter

- templates/quickstart-confluence-master-with-vpc.template.yaml
- templates/quickstart-confluence-master.template.yaml
This PR corrects the Type used by KeyPairName.
> KeyPairName syntax correction

- templates/quickstart-confluence-master-with-vpc.template.yaml
- templates/quickstart-confluence-master.template.yaml
> Fix parameter defaults to match parameter type

- templates/quickstart-confluence-master-with-vpc.template.yaml
- templates/quickstart-confluence-master.template.yaml
Updates to the password criteria descriptions, specifically in relation to what special characters are allowed, relating to the params: 
- `DBPassword`
- `DBMasterUserPassword`
> Update password criteria descriptions

- templates/quickstart-confluence-master-with-vpc.template.yaml
- templates/quickstart-confluence-master.template.yaml
Minor update to the description for the param `DBPassword`
> Update password descriptions

- templates/quickstart-confluence-master-with-vpc.template.yaml
- templates/quickstart-confluence-master.template.yaml
All resources were allow to perform actions in ConfluenceClusterNodePolicy. The changes permits to only resources of the certain account.
> Fixed the IAM role security concern

- templates/quickstart-confluence-master-with-vpc.template.yaml
- templates/quickstart-confluence-master.template.yaml
> DCD-1434: Added description for deprecated DBEngineVersion

- .cfnlintrc
- templates/quickstart-confluence-master.template.yaml
*DCD-1361, DCD-1459. Description of changes:*
Updated all AMI IDs to the latest available release.
Fixed ASI documentation link.
> Update AMI IDs in all regions

- docs/partner_editable/_clone_quickstart.adoc
- templates/quickstart-confluence-master.template.yaml
*DCD-1361*
*Remove redundant step from S3 template instructions.*
> DCD-1361 Remove redundant step from S3 template instructions
